version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api_network
  
  web:
    build: .
    command: bash -c "./bin/setup.sh"
    # volumes:
    #   - home:
    ports:
      - 4567:4567
    depends_on:
      - db
    networks:
      - api_network
  
volumes:
  db_data:

networks:
  api_network:
