version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3308:3306
    environment:
      MYSQL_DATABASE: my_db_name
      MYSQL_ROOT_PASSWORD: my_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_network

    # image: postgres
    # restart: always
    # environment:
    #   POSTGRES_PASSWORD: 123456
    
    
  web:
    build: .
    command: bash -c "./bin/setup.sh"
    volumes:
      - .:/home
    ports:
      - 4567:4567
    depends_on:
      - db
    networks:
      - api_network

      
    #docker rmi -f $(docker images -aq)

volumes:
  db_data:

networks:
  api_network:
