# frozen_string_literal: true

# File contains gems for DB, Api and testing

source 'https://rubygems.org'

gem 'pg'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-logger'

gem 'faraday'
gem 'pry'
gem 'rspec'
gem "rspec_junit_formatter"

gem 'parallel_tests'
gem 'reek'

gem 'http'
gem 'puma'
gem 'reel'
gem 'thin'
gem 'webrick'
